travis:
  secure:
    BINSTAR_TOKEN: 2ifkClU0uj66ODvEZRUflfpgrObdxLpIGoJRVj1DgEMcIVr5gR10Z7XBjfgZNzhikPw7HcRMppR0iZWsmJ+Jxwtj4RvaegFpf723N0aMVrKlt/P6E9kyMsrEnQIG08CiYxQcSH1G+lj/OSiiFdw0aZFvumW/CN5fSFIfD7QpPAGpDEOBev6rCTt9P6HiD+VF194lfyC2yIW175nKhnzXi3wHwULvZMnSPSoSRnTVKbQarJNm4QnPsHFN0QwUnPQ8pnDXrgSRFqnajQ7YdTWaHQ9fwhxIokmNN9kFpioJFhn2OuA28qbsquJ+0q+Vy3USu88eVSpsIs/TXz/8vu0HCfhqDLZBEkimuwdkk3pSIY77NNYDhv+RTbZXrQNVp1Oy4hRxzXgu+iLKtfR8w1bq+Fzph9KTR2HAMsiA0cJIqCUyOqg5asX3DME7J2fuF30jk5UYJoM2+lPbDvzvUjkeCAWfd7IS69lYjCFs3UG+alh0Jy3ylVMklWEnzNrjj5Y4HjTi5DbfhKZXfEJ27cPyq3Q3U+ZPyjGizZJfwC/efnGdTVYfKmJjjpZV9wrMcSZ1RvrxXe7/cWk1Xed86mETHmbiuBZrABIoSMQKVW4SW5+DXGC2kc1aKj18utWh4eb4NAuRvrKGSnrkkkddeedb63xAPk1jy1iNWpHXQR5CueI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
